### ISSUE TITLE
V_HOST config error for proxy buffering

### ISSUE THREAD

**Issue by ctangney-tulip** [Upstatement/ups-dock#23]
# Description
In cases where a site connecting to ups.dock has a header which is too large (cookies / etc), nginx returns an `upstream sent too big header while reading response` error.

Per the documentation for the [jwilder/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy#per-virtual_host) image, it is possible to adjust the per-host / default `proxy_buffer` sizing by providing a configuration file in the `/etc/nginx/vhost.d/` directory.

At the moment, there does not appear to be a means to accomplish this via the available configurations. I was able to accomplish this by manually editing the `Dockerfile` to create a `~/vhost.d/default` file with the settings I needed.

## Steps to reproduce
This was easily reproduced on log-ins to a Craft CMS instance which contained a large cookie. Additionally, this can sometimes be reproduced when performing large write operations to the `db`.

1. Create a request to a site connecting to ups.dock (cURL, fetch, etc). Ensure it is of large enough size to exceed nginx's default proxy buffer size
2. Send the request
3. Observe that server error is thrown (in our case, a 502)
4. In the `nginx` logs, observe that an `upstream sent too big header while reading response header from upstream` is thrown, referencing route.

## Expected result
No error is thrown; nginx performs the expected action.

## Actual result
Error is thrown.

## Environment
- Docker version: v4.10.1

**Comment by ctangney-tulip** [comment]
I would expect either:
- `nginx` is properly configured on a global scale to allow for larger-than-default proxy buffer sizing, or;
- ups.dock configuration enables users to set dynamic proxy buffer sizes as needed, on a per-instance basis

**Comment by mgburns** [comment]
Closed by #24 -- thanks @ctangney-tulip!
